# Generated by Django 5.0.1 on 2024-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(default=0)),
                ('Location', models.CharField(max_length=100)),
                ('Leave', models.IntegerField(default=0)),
            ],
        ),
    ]
