# Generated by Django 5.0.1 on 2024-02-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.CreateModel(
            name='PaySlips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaySlips', models.FileField(upload_to='payslips')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_slips', to='Auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(upload_to='resume')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='Auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StackCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StackCertificate', models.FileField(upload_to='stack_certificates')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_certificate', to='Auth.profile')),
            ],
        ),
    ]
