# Generated by Django 5.0.1 on 2024-01-29 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')),
                ('location', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='profile_cv')),
                ('certificates', models.FileField(upload_to='certificates')),
                ('paydetails', models.ImageField(upload_to='paydetails')),
                ('Leave', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
