# Generated by Django 5.0.1 on 2024-02-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_profile_file_remove_profile_image_payslips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslips',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='Auth.profile'),
        ),
        migrations.AlterField(
            model_name='stackcertificate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stackcertificate', to='Auth.profile'),
        ),
    ]
