# Generated by Django 5.0.1 on 2024-01-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_appuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
