# Generated by Django 5.0.1 on 2024-02-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_profile_file_remove_profile_image_filemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Auth.profile'),
        ),
    ]
