# Generated by Django 5.0.1 on 2024-02-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_publication_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
